# Generated by Django 4.1.7 on 2023-03-17 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('codename', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150, unique=True)),
                ('first_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150)),
                ('last_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150)),
                ('email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='client_Id', max_length=10, primary_key=True, serialize=False)),
                ('client_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=25, null=True)),
                ('email', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=35, null=True)),
                ('residential_address', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('password_hash', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=256)),
            ],
            options={
                'db_table': 'Client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientPurchase',
            fields=[
                ('purchase_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, primary_key=True, serialize=False)),
                ('price', models.FloatField(blank=True, null=True)),
                ('commission', models.FloatField(blank=True, null=True)),
                ('date_sold', models.DateField(blank=True, null=True)),
                ('amt_paid', models.FloatField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=15, null=True)),
            ],
            options={
                'db_table': 'Client_Purchase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('object_repr', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('model', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_contact_number', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=15, null=True)),
            ],
            options={
                'db_table': 'Emergency_Contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='emp_Id', max_length=10, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=25)),
                ('date_employed', models.DateField()),
                ('dob', models.DateField()),
                ('password_hash', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=256)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpPurchase',
            fields=[
                ('purchase_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, primary_key=True, serialize=False)),
                ('date_sold', models.DateField(blank=True, null=True)),
                ('vehicle_value', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Emp_Purchase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Useraccesslog',
            fields=[
                ('accesslogid', models.AutoField(db_column='AccessLogID', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='UserName', max_length=50, null=True)),
                ('accesstime', models.DateTimeField(blank=True, db_column='AccessTime', null=True)),
                ('datatablename', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DataTableName', max_length=255, null=True)),
                ('eventtype', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='EventType', max_length=100, null=True)),
            ],
            options={
                'db_table': 'UserAccessLog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('chassis_number', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, primary_key=True, serialize=False)),
                ('make', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
                ('import_price_usd', models.FloatField(blank=True, null=True)),
                ('car_year', models.DateField(blank=True, null=True)),
                ('markup_percent', models.FloatField(blank=True, null=True)),
                ('colour', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=15, null=True)),
                ('engine_number', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('model', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=15, null=True)),
                ('car_type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=15, null=True)),
                ('condition', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('mileage', models.FloatField(blank=True, null=True)),
                ('cc_rating', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=5, null=True)),
            ],
            options={
                'db_table': 'Vehicle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkDone',
            fields=[
                ('work_done_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, primary_key=True, serialize=False)),
                ('hrs_worked', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Work_Done',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('work_done', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='drauto.workdone')),
                ('addon_description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='addOn_description', max_length=50, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Add_On',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminPersonnel',
            fields=[
                ('emp', models.OneToOneField(db_column='emp_Id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='drauto.employee')),
                ('salary', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Admin_Personnel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('chassis_number', models.OneToOneField(db_column='chassis_number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='drauto.vehicle')),
                ('seat_capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Car',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FourWd',
            fields=[
                ('chassis_number', models.OneToOneField(db_column='chassis_number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='drauto.vehicle')),
                ('vehicle_size', models.FloatField(blank=True, null=True)),
                ('fuel_type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Four_WD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('emp', models.OneToOneField(db_column='emp_Id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='drauto.employee')),
                ('salary', models.FloatField(blank=True, null=True)),
                ('expertise', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=25, null=True)),
            ],
            options={
                'db_table': 'Mechanic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PartsChanged',
            fields=[
                ('work_done', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='drauto.workdone')),
                ('part_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=15, null=True)),
                ('part_description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=15, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Parts_Changed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('phone_number', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=15, null=True)),
                ('client', models.OneToOneField(db_column='client_Id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='drauto.client')),
            ],
            options={
                'db_table': 'Phone_Number',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('work_done', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='drauto.workdone')),
                ('repair_description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Repair',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('emp', models.OneToOneField(db_column='emp_Id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='drauto.employee')),
                ('travel_subsistence', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Salesman',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('emp', models.OneToOneField(db_column='emp_Id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='drauto.employee')),
                ('date_assigned', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Supervisor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Van',
            fields=[
                ('chassis_number', models.OneToOneField(db_column='chassis_number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='drauto.vehicle')),
                ('haul_capacity', models.FloatField(blank=True, null=True)),
                ('max_clearance', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Van',
                'managed': False,
            },
        ),
    ]
